### PR TITLE
always capture eval error when call retry if

### PR DESCRIPTION
**Pull request by karupanerura**
When using `retry_if` callback, the exception propagation is not works.

The previous implementation collects exception by default `retry_if` callback.
So it veils the exception that occurred in the main callback when `retry_if` callback is override.

I think exceptions should always be propagated, as this causes problems that are hard to notice.

### CODE REVIEW

**Comment by karupanerura** [comment]
the CI job failed. but it looks old perl CI environments are broken.

**Comment by tokuhirom** [comment]
could you add test code?

**Comment by tokuhirom** [comment]
(I fixed .travis.yml in master branch.

**Comment by karupanerura** [comment]
Thank you to check it. added test cases about dead in the main callback

**Review by tokuhirom — APPROVED** [review]
thanks!

**Pull request merged**
